import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, ArrowRight, Check, LoaderCircle, Plus, X } from 'lucide-react';
import SectionHeading from '../components/SectionHeading';
import { useApp } from '../context/AppContext';

const steps = ['Decision basics','Options & context','Your reasoning','Review & analyze'];

export default function NewAnalysis(){
  const { api, setDecision, setAnalysis, refreshHistory } = useApp(); const navigate=useNavigate(); const [step,setStep]=useState(0); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
  const [form,setForm]=useState({ title:'', decision:'', options:['',''], priorities:[], priorityInput:'', reasons:'', constraints:'', known_facts:'' });
  const update=(k,v)=>setForm(f=>({...f,[k]:v}));
  const options=form.options;
  const canNext=useMemo(()=>step===0?form.decision.trim().length>=10:step===1?options.filter(Boolean).length>=1:step===2?form.reasons.trim().length>=10:true,[step,form.decision,form.reasons,options]);
  const next=()=>{setError(''); if(canNext)setStep(s=>Math.min(3,s+1)); else setError(step===0?'Tell us what decision you are considering.':step===1?'Add at least one option.':'Give a little more detail about your reasoning.');};
  const run=async()=>{setLoading(true);setError(''); try { const payload={decision:form.decision,options:options.map(x=>x.trim()).filter(Boolean),priorities:form.priorities,constraints:form.constraints,known_facts:form.known_facts,reasons:form.reasons}; const result=await api('/api/v1/analysis/audit',{method:'POST',body:JSON.stringify({title:form.title.trim() || form.decision.slice(0,44), ...payload})}); setDecision(result.decision); setAnalysis(result.analysis); await refreshHistory(); navigate('/results'); } catch(e){setError(e.message)} finally{setLoading(false)} };
  const addPriority=()=>{const p=form.priorityInput.trim();if(p){update('priorities',[...form.priorities,p]);update('priorityInput','')}};
  return <main className="workspace-page analysis-page"><SectionHeading eyebrow="NEW DECISION ANALYSIS" title="Let's put this decision under the lens." text="You don't need perfect information. Tell us the reasoning you are currently using, including the parts you may be uncertain about."/>
    <div className="wizard-wrap"><aside className="wizard-rail"><span className="wizard-title">ANALYSIS FLOW</span>{steps.map((s,i)=><button key={s} className={i===step?'wizard-step active':i<step?'wizard-step done':'wizard-step'} onClick={()=>i<=step&&setStep(i)} type="button"><span>{i<step?<Check size={14}/>:i+1}</span><div><b>{s}</b><small>{i===0?'The decision':i===1?'What you can choose':i===2?'Why you lean': 'Final check'}</small></div></button>)}<div className="wizard-rule"><span>NOTE</span><p>MindXray looks for gaps in reasoning. It never returns a “best choice”.</p></div></aside>
    <section className="wizard-card">
      {step===0&&<div className="step-body"><span className="eyebrow">STEP 1 OF 4</span><h2>Decision basics</h2><p className="step-intro">Start with the decision itself. Name it clearly enough that a stranger could understand it.</p><label>Give this analysis a short title<input value={form.title} onChange={e=>update('title',e.target.value)} placeholder="e.g. 6-Month Internship Decision"/></label><label>What decision are you considering? <span>*</span><textarea autoFocus value={form.decision} onChange={e=>update('decision',e.target.value)} placeholder="e.g. Should I accept this 6-month internship?"/></label></div>}
      {step===1&&<div className="step-body"><span className="eyebrow">STEP 2 OF 4</span><h2>Options & context</h2><p className="step-intro">List the real choices on the table and the priorities you care about.</p><label>Your options <span>*</span>{options.map((o,i)=><div className="option-row" key={i}><span>{i+1}</span><input value={o} onChange={e=>update('options',options.map((x,j)=>j===i?e.target.value:x))} placeholder={`Option ${i+1}`}/>{options.length>1&&<button type="button" onClick={()=>update('options',options.filter((_,j)=>j!==i))}><X size={15}/></button>}</div>)}<button type="button" className="add-link" onClick={()=>options.length<8&&update('options',[...options,''])}><Plus size={15}/> Add another option</button></label><label>What matters most to you?<div className="priority-add"><input value={form.priorityInput} onChange={e=>update('priorityInput',e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addPriority()}}} placeholder="e.g. learning, time, money"/><button type="button" onClick={addPriority}><Plus/></button></div><div className="chips">{form.priorities.map(p=><button type="button" key={p} className="chip" onClick={()=>update('priorities',form.priorities.filter(x=>x!==p))}>{p} ×</button>)}</div></label></div>}
      {step===2&&<div className="step-body"><span className="eyebrow">STEP 3 OF 4</span><h2>Your reasoning</h2><p className="step-intro">This is the most valuable part. Tell us why you currently lean one way, even if some of the reasoning feels subjective.</p><label>Why are you leaning toward your current thinking? <span>*</span><textarea autoFocus value={form.reasons} onChange={e=>update('reasons',e.target.value)} placeholder="I'm mainly considering this because..."/></label><div className="two-field"><label>Constraints / concerns<textarea value={form.constraints} onChange={e=>update('constraints',e.target.value)} placeholder="Time, money, academics, location, family..."/></label><label>Known facts<textarea value={form.known_facts} onChange={e=>update('known_facts',e.target.value)} placeholder="Verified facts only. Separate them from your assumptions."/></label></div></div>}
      {step===3&&<div className="step-body"><span className="eyebrow">STEP 4 OF 4</span><h2>Review & analyze</h2><p className="step-intro">Check what MindXray will receive before the AI reasoning audit starts.</p><div className="review-card"><div><span>DECISION</span><strong>{form.decision}</strong></div><div><span>OPTIONS</span><p>{options.filter(Boolean).join(' · ')}</p></div><div><span>PRIORITIES</span><p>{form.priorities.length?form.priorities.join(' · '):'None added'}</p></div><div><span>REASONING</span><p>{form.reasons}</p></div><div className="review-note"><Check size={17}/> MindXray will identify assumptions, blind spots, conflicts, evidence gaps and critical questions.</div></div></div>}
      {error&&<div className="error-banner" role="alert">{error}</div>}
      <div className="wizard-footer">{step>0?<button className="btn soft" type="button" onClick={()=>setStep(s=>s-1)}><ArrowLeft size={17}/> Previous</button>:<span></span>}{step<3?<button className="btn gold" type="button" onClick={next}>Next <ArrowRight size={17}/></button>:<button className="btn gold" type="button" onClick={run} disabled={loading}>{loading?<><LoaderCircle className="spin"/> X-raying…</>:<>Run Reasoning X-Ray <ArrowRight size={17}/></>}</button>}</div>
    </section></div>
  </main>;
}
