import { useEffect, useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { ArrowLeft, CheckCircle2, FlaskConical, LoaderCircle, SearchCheck } from 'lucide-react';
import SectionHeading from '../components/SectionHeading';
import { useApp } from '../context/AppContext';

export default function StressTest(){
  const { state }=useLocation(); const {api,decision,analysis}=useApp(); const [assumption,setAssumption]=useState(state?.assumption||''); const [result,setResult]=useState(null); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
  useEffect(()=>{ if(state?.assumption)setAssumption(state.assumption); },[state?.assumption]);
  const run=async()=>{if(!assumption.trim())return setError('Enter an assumption.');setLoading(true);setError('');try{setResult(await api('/api/v1/analysis/stress-test',{method:'POST',body:JSON.stringify({assumption,context:`Decision: ${decision?.decision||''}\nReasoning: ${decision?.reasons||''}\nFacts: ${decision?.known_facts||''}`,analysis_id: analysis?.id})}));}catch(e){setError(e.message)}finally{setLoading(false)}};
  return <main className="workspace-page stress-page"><Link to="/results" className="crumb-back"><ArrowLeft size={15}/> Back to X-Ray</Link><SectionHeading eyebrow="SIGNATURE FEATURE · ASSUMPTION STRESS TEST" title="Don't trust the assumption. Test it." text="Explore what could make it true, what could make it fail, and what evidence would actually settle the question."/><div className="stress-layout-pro"><aside className="stress-editor"><span className="eyebrow">THE ASSUMPTION</span><textarea value={assumption} onChange={e=>setAssumption(e.target.value)} placeholder="e.g. This internship will meaningfully improve my career prospects."/><button className="btn gold full" onClick={run} disabled={loading}>{loading?<><LoaderCircle className="spin"/> Testing…</>:<><FlaskConical size={17}/> Stress-test assumption</>}</button>{error&&<div className="error-banner">{error}</div>}<div className="stress-sidebar-note"><SearchCheck size={17}/><p>The goal is not to prove the assumption wrong. It's to make its weak points visible.</p></div></aside>{result?<section className="stress-results-pro"><div className="stress-two"><article className="stress-card positive"><span>IF IT HOLDS</span><h3>Why it may be true</h3><p>{result.why_it_may_hold}</p></article><article className="stress-card negative"><span>IF IT FAILS</span><h3>Why it may break</h3><p>{result.why_it_may_fail}</p></article></div><article className="stress-card"><div className="stress-card-head"><CheckCircle2/><div><span>EVIDENCE TO SEEK</span><h3>What would help verify it?</h3></div></div><ul>{result.evidence_to_seek.map((x,i)=><li key={i}>{x}</li>)}</ul></article><article className="stress-card"><div className="stress-card-head"><SearchCheck/><div><span>QUESTIONS TO ASK</span><h3>What should you investigate?</h3></div></div><ul>{result.questions_to_ask.map((x,i)=><li key={i}>{x}</li>)}</ul></article><article className="stress-card wide"><div className="stress-card-head"><FlaskConical/><div><span>VERIFICATION PLAN</span><h3>How to test this in the real world</h3></div></div><ol>{result.verification_steps.map((x,i)=><li key={i}><span>{i+1}</span>{x}</li>)}</ol></article></section>:<div className="stress-empty"><div className="stress-empty-orb"><FlaskConical size={34}/></div><h2>Your stress test appears here.</h2><p>Select an assumption from the X-Ray or write one above.</p></div>}</div></main>;
}
